"""
Auto-generated mappings from Rosetta Stone CSVs.
Provides dictionary layouts for SCS and STS servos.
"""

SCS_MEMORY_MAP = {
    0: {'name': 'Firmware Main Version', 'size': 1, 'signed_bit': None, 'area': 'EPROM', 'rw': 'r'},
    1: {'name': 'Firmware Secondary Version', 'size': 1, 'signed_bit': None, 'area': 'EPROM', 'rw': 'r'},
    3: {'name': 'Servo Main Version', 'size': 1, 'signed_bit': None, 'area': 'EPROM', 'rw': 'r'},
    4: {'name': 'Servo Sub Version', 'size': 1, 'signed_bit': None, 'area': 'EPROM', 'rw': 'd'},
    5: {'name': 'ID', 'size': 1, 'signed_bit': None, 'area': 'EPROM', 'rw': 'rw'},
    6: {'name': 'Baud Rate', 'size': 1, 'signed_bit': None, 'area': 'EPROM', 'rw': 'rw'},
    7: {'name': 'Reserved', 'size': 1, 'signed_bit': None, 'area': 'EPROM', 'rw': 'rw'},
    8: {'name': 'Status Return Level', 'size': 1, 'signed_bit': None, 'area': 'EPROM', 'rw': 'rw'},
    9: {'name': 'Min Position Limit', 'size': 2, 'signed_bit': None, 'area': 'EPROM', 'rw': 'rw'},
    11: {'name': 'Max Position Limit', 'size': 2, 'signed_bit': None, 'area': 'EPROM', 'rw': 'rw'},
    13: {'name': 'Max Temperature limit', 'size': 1, 'signed_bit': None, 'area': 'EPROM', 'rw': 'rw'},
    14: {'name': 'Max Input Voltage', 'size': 1, 'signed_bit': None, 'area': 'EPROM', 'rw': 'rw'},
    15: {'name': 'Min Input Voltage', 'size': 1, 'signed_bit': None, 'area': 'EPROM', 'rw': 'rw'},
    16: {'name': 'Max Torque Limit', 'size': 2, 'signed_bit': None, 'area': 'EPROM', 'rw': 'rw'},
    19: {'name': 'Protection Switch', 'size': 1, 'signed_bit': None, 'area': 'EPROM', 'rw': 'rw'},
    20: {'name': 'LED Alarm Condition', 'size': 1, 'signed_bit': None, 'area': 'EPROM', 'rw': 'rw'},
    21: {'name': 'Position P Gain', 'size': 1, 'signed_bit': None, 'area': 'EPROM', 'rw': 'rw'},
    22: {'name': 'Position D Gain', 'size': 1, 'signed_bit': None, 'area': 'EPROM', 'rw': 'rw'},
    23: {'name': 'Position I Gain', 'size': 1, 'signed_bit': None, 'area': 'EPROM', 'rw': 'rw'},
    24: {'name': 'Punch', 'size': 2, 'signed_bit': None, 'area': 'EPROM', 'rw': 'rw'},
    26: {'name': 'CW Dead Band', 'size': 1, 'signed_bit': None, 'area': 'EPROM', 'rw': 'rw'},
    27: {'name': 'CCW Dead Band', 'size': 1, 'signed_bit': None, 'area': 'EPROM', 'rw': 'rw'},
    37: {'name': 'Protect Torque', 'size': 1, 'signed_bit': None, 'area': 'EPROM', 'rw': 'rw'},
    38: {'name': 'Overload Protection Time', 'size': 1, 'signed_bit': None, 'area': 'EPROM', 'rw': 'rw'},
    39: {'name': 'Overload Torque', 'size': 1, 'signed_bit': None, 'area': 'EPROM', 'rw': 'rw'},
    40: {'name': 'Torque Enable', 'size': 1, 'signed_bit': None, 'area': 'SRAM', 'rw': 'rw'},
    42: {'name': 'Goal Position', 'size': 2, 'signed_bit': None, 'area': 'SRAM', 'rw': 'rw'},
    44: {'name': 'Running Time', 'size': 2, 'signed_bit': None, 'area': 'SRAM', 'rw': 'rw'},
    46: {'name': 'Goal Velocity', 'size': 2, 'signed_bit': None, 'area': 'SRAM', 'rw': 'rw'},
    48: {'name': 'Lock', 'size': 1, 'signed_bit': None, 'area': 'SRAM', 'rw': 'rw'},
    56: {'name': 'Present Position', 'size': 2, 'signed_bit': None, 'area': 'SRAM', 'rw': 'r'},
    58: {'name': 'Present Velocity', 'size': 2, 'signed_bit': None, 'area': 'SRAM', 'rw': 'r'},
    60: {'name': 'Present PWM', 'size': 2, 'signed_bit': None, 'area': 'SRAM', 'rw': 'r'},
    62: {'name': 'Present Input Voltage', 'size': 1, 'signed_bit': None, 'area': 'SRAM', 'rw': 'r'},
    63: {'name': 'Present Temperature', 'size': 1, 'signed_bit': None, 'area': 'SRAM', 'rw': 'r'},
    64: {'name': 'Sync Write Flag', 'size': 1, 'signed_bit': None, 'area': 'SRAM', 'rw': 'r'},
    65: {'name': 'Hardware Error Status', 'size': 1, 'signed_bit': None, 'area': 'SRAM', 'rw': 'r'},
    66: {'name': 'Moving Status', 'size': 1, 'signed_bit': None, 'area': 'SRAM', 'rw': 'r'},
    78: {'name': 'PWM Mode Acc', 'size': 1, 'signed_bit': None, 'area': 'DEFAULT', 'rw': 'd'},
    79: {'name': 'Moving Threshold', 'size': 1, 'signed_bit': None, 'area': 'DEFAULT', 'rw': 'd'},
    80: {'name': 'DTs(ms)', 'size': 1, 'signed_bit': None, 'area': 'DEFAULT', 'rw': 'd'},
    81: {'name': 'Vmin', 'size': 1, 'signed_bit': None, 'area': 'DEFAULT', 'rw': 'd'},
    82: {'name': 'Vmax', 'size': 1, 'signed_bit': None, 'area': 'DEFAULT', 'rw': 'd'},
    83: {'name': 'Amax', 'size': 1, 'signed_bit': None, 'area': 'DEFAULT', 'rw': 'd'},
}

STS_MEMORY_MAP = {
    0: {'name': 'Firmware Main Version', 'size': 1, 'signed_bit': None, 'area': 'EPROM', 'rw': 'r'},
    1: {'name': 'Firmware Secondary Version', 'size': 1, 'signed_bit': None, 'area': 'EPROM', 'rw': 'r'},
    3: {'name': 'Servo Main Version', 'size': 1, 'signed_bit': None, 'area': 'EPROM', 'rw': 'r'},
    4: {'name': 'Servo Sub Version', 'size': 1, 'signed_bit': None, 'area': 'EPROM', 'rw': 'd'},
    5: {'name': 'ID', 'size': 1, 'signed_bit': None, 'area': 'EPROM', 'rw': 'rw'},
    6: {'name': 'Baud Rate', 'size': 1, 'signed_bit': None, 'area': 'EPROM', 'rw': 'rw'},
    7: {'name': 'Reserved', 'size': 1, 'signed_bit': None, 'area': 'EPROM', 'rw': 'rw'},
    8: {'name': 'Status Return Level', 'size': 1, 'signed_bit': None, 'area': 'EPROM', 'rw': 'rw'},
    9: {'name': 'Min Position Limit', 'size': 2, 'signed_bit': 15, 'area': 'EPROM', 'rw': 'rw'},
    11: {'name': 'Max Position Limit', 'size': 2, 'signed_bit': 15, 'area': 'EPROM', 'rw': 'rw'},
    13: {'name': 'Max Temperature limit', 'size': 1, 'signed_bit': None, 'area': 'EPROM', 'rw': 'rw'},
    14: {'name': 'Max Input Voltage', 'size': 1, 'signed_bit': None, 'area': 'EPROM', 'rw': 'rw'},
    15: {'name': 'Min Input Voltage', 'size': 1, 'signed_bit': None, 'area': 'EPROM', 'rw': 'rw'},
    16: {'name': 'Max Torque Limit', 'size': 2, 'signed_bit': None, 'area': 'EPROM', 'rw': 'rw'},
    18: {'name': 'Setting Byte', 'size': 1, 'signed_bit': None, 'area': 'EPROM', 'rw': 'rw'},
    19: {'name': 'Protection Switch', 'size': 1, 'signed_bit': None, 'area': 'EPROM', 'rw': 'rw'},
    20: {'name': 'LED Alarm Condition', 'size': 1, 'signed_bit': None, 'area': 'EPROM', 'rw': 'rw'},
    21: {'name': 'Position P Gain', 'size': 1, 'signed_bit': None, 'area': 'EPROM', 'rw': 'rw'},
    22: {'name': 'Position D Gain', 'size': 1, 'signed_bit': None, 'area': 'EPROM', 'rw': 'rw'},
    23: {'name': 'Position I Gain', 'size': 1, 'signed_bit': None, 'area': 'EPROM', 'rw': 'rw'},
    24: {'name': 'Punch', 'size': 2, 'signed_bit': None, 'area': 'EPROM', 'rw': 'rw'},
    25: {'name': 'MAX I', 'size': 1, 'signed_bit': None, 'area': 'EPROM', 'rw': 'rw'},
    26: {'name': 'CW Dead Band', 'size': 1, 'signed_bit': None, 'area': 'EPROM', 'rw': 'rw'},
    27: {'name': 'CCW Dead Band', 'size': 1, 'signed_bit': None, 'area': 'EPROM', 'rw': 'rw'},
    28: {'name': 'Overload Current', 'size': 2, 'signed_bit': None, 'area': 'EPROM', 'rw': 'rw'},
    30: {'name': 'Angular Resolution', 'size': 1, 'signed_bit': None, 'area': 'EPROM', 'rw': 'rw'},
    31: {'name': 'Position Offset Value', 'size': 2, 'signed_bit': 15, 'area': 'EPROM', 'rw': 'rw'},
    33: {'name': 'Work Mode', 'size': 1, 'signed_bit': None, 'area': 'EPROM', 'rw': 'rw'},
    34: {'name': 'Protect Torque', 'size': 1, 'signed_bit': None, 'area': 'EPROM', 'rw': 'rw'},
    35: {'name': 'Overload Protection Time', 'size': 1, 'signed_bit': None, 'area': 'EPROM', 'rw': 'rw'},
    36: {'name': 'Overload Torque', 'size': 1, 'signed_bit': None, 'area': 'EPROM', 'rw': 'rw'},
    37: {'name': 'Velocity P Gain', 'size': 1, 'signed_bit': None, 'area': 'EPROM', 'rw': 'rw'},
    38: {'name': 'Overcurrent Protection', 'size': 1, 'signed_bit': None, 'area': 'EPROM', 'rw': 'rw'},
    39: {'name': 'Velocity I Gain', 'size': 1, 'signed_bit': None, 'area': 'EPROM', 'rw': 'rw'},
    40: {'name': 'Torque Enable', 'size': 1, 'signed_bit': None, 'area': 'SRAM', 'rw': 'rw'},
    41: {'name': 'Goal Acceleration', 'size': 1, 'signed_bit': None, 'area': 'SRAM', 'rw': 'rw'},
    42: {'name': 'Goal Position', 'size': 2, 'signed_bit': None, 'area': 'SRAM', 'rw': 'rw'},
    44: {'name': 'Goal PWM', 'size': 2, 'signed_bit': 10, 'area': 'SRAM', 'rw': 'rw'},
    46: {'name': 'Goal Velocity', 'size': 2, 'signed_bit': 15, 'area': 'SRAM', 'rw': 'rw'},
    48: {'name': 'Torque Limit', 'size': 2, 'signed_bit': None, 'area': 'SRAM', 'rw': 'rw'},
    55: {'name': 'Lock', 'size': 1, 'signed_bit': None, 'area': 'SRAM', 'rw': 'rw'},
    56: {'name': 'Present Position', 'size': 2, 'signed_bit': None, 'area': 'SRAM', 'rw': 'r'},
    58: {'name': 'Present Velocity', 'size': 2, 'signed_bit': 15, 'area': 'SRAM', 'rw': 'r'},
    60: {'name': 'Present PWM', 'size': 2, 'signed_bit': None, 'area': 'SRAM', 'rw': 'r'},
    62: {'name': 'Present Input Voltage', 'size': 1, 'signed_bit': None, 'area': 'SRAM', 'rw': 'r'},
    63: {'name': 'Present Temperature', 'size': 1, 'signed_bit': None, 'area': 'SRAM', 'rw': 'r'},
    64: {'name': 'Sync Write Flag', 'size': 1, 'signed_bit': None, 'area': 'SRAM', 'rw': 'r'},
    65: {'name': 'Hardware Error Status', 'size': 1, 'signed_bit': None, 'area': 'SRAM', 'rw': 'r'},
    66: {'name': 'Moving Status', 'size': 1, 'signed_bit': None, 'area': 'SRAM', 'rw': 'r'},
    69: {'name': 'Present Current', 'size': 2, 'signed_bit': None, 'area': 'SRAM', 'rw': 'r'},
    80: {'name': 'Moving Threshold', 'size': 1, 'signed_bit': None, 'area': 'DEFAULT', 'rw': 'd'},
    81: {'name': 'DTs(ms)', 'size': 1, 'signed_bit': None, 'area': 'DEFAULT', 'rw': 'd'},
    82: {'name': 'Vk(ms)', 'size': 1, 'signed_bit': None, 'area': 'DEFAULT', 'rw': 'd'},
    83: {'name': 'Vmin', 'size': 1, 'signed_bit': None, 'area': 'DEFAULT', 'rw': 'd'},
    84: {'name': 'Vmax', 'size': 1, 'signed_bit': None, 'area': 'DEFAULT', 'rw': 'd'},
    85: {'name': 'Amax', 'size': 1, 'signed_bit': None, 'area': 'DEFAULT', 'rw': 'd'},
    86: {'name': 'KAcc', 'size': 1, 'signed_bit': None, 'area': 'DEFAULT', 'rw': 'd'},
}
